### ISSUE TITLE
Getting "export 'Controller' (imported as 'o') was not found in

### ISSUE THREAD

**Issue by waynehoover** [stimulus-components/stimulus-popover#15]
Hello,

I am getting this error when adding `import Popover from 'stimulus-popover'` to my `controllers/index.js` file. I'm using webpacker. Any idea how to fix it? Thanks!

```
ERROR in ./node_modules/stimulus-popover/dist/stimulus-popover.mjs 157:2-3
"export 'Controller' (imported as 'o') was not found in '@hotwired/stimulus'
    at HarmonyImportSpecifierDependency._getErrors (/Users/wayne/code/kode/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:109:11)
    at HarmonyImportSpecifierDependency.getErrors (/Users/wayne/code/kode/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/wayne/code/kode/node_modules/webpack/lib/Compilation.js:1463:22)
    at /Users/wayne/code/kode/node_modules/webpack/lib/Compilation.js:1258:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/wayne/code/kode/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/wayne/code/kode/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/Users/wayne/code/kode/node_modules/webpack/lib/Compilation.js:1253:28)
    at /Users/wayne/code/kode/node_modules/webpack/lib/Compiler.js:672:17
    at _done (eval at create (/Users/wayne/code/kode/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at eval (eval at create (/Users/wayne/code/kode/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:22)
```

**Comment by guillaumebriday** [comment]
Hum, did you install `@hotwired/stimulus`? and which version of webpack do you use?

**Comment by aliciapaz** [comment]
I'm getting the same error in a Rails 6.1 app with Webpack. 
Gemfile: 
```
gem 'webpacker', '~> 5.0'
```

package.json:
```
    "@hotwired/stimulus": "^3.0.1",
    "stimulus-popover": "^6.2.0",
    "webpack": "^4.46.0",
```

I tried with different versions of the gem and the webpack package, same error.
